name: React CI Workflow

# When to trigger the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs to run
jobs:
  build:
    # OS to run the workflow on
    runs-on: ubuntu-latest

    # Define steps
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js (specify the version)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # You can specify the version you want

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (if any)
      - name: Run tests
        run: npm test

      # Build the project
      - name: Build project
        run: npm run build
